export { default as Login } from "./login"
export { default as Register } from "./register"
export { default as ForgotPassword } from "./forgot-Password"
export { default as ChangePassword } from "./change-password"
export { default as ResetPassword } from "./reset-password"